<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Template</title>
        <link rel="stylesheet" href="/assets/bootstrap/css/bootstrap.min.css">
        <link rel="stylesheet" href="/assets/bootstrap/css/bootstrap-theme.min.css">
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-static-top">
          <div class="container-fluid">
              <ul class="nav navbar-nav">
                  <li><a href="#">Home</a></li>
              </ul>
          </div>
        </nav>

        <div class="container">
            <?php echo $this->getContent(); ?>
        </div>

        <script src="/assets/bootstrap/js/bootstrap.min.js"></script>

    </body>
</html>
