<h1>Nouvel utilisateur</h1>

<?php if (!empty($errors)) : ?> 
<div class="alert alert-danger">
    <ul>
    <?php foreach ($errors as $error) : ?>
        <?php foreach ($error as $message) : ?>
            <li><?= $message ?></li>
        <?php endforeach; ?>
    <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>

<form method="POST">

    <div class="form-group">
        <input class="form-control" type="text" name="username" value="<?= $user['username'] ?>" placeholder="Nom d'utilisateur" />
    </div>

    <div class="form-group">
        <input class="form-control" type="password" name="password" value="<?= $user['password'] ?>" placeholder="Mot de passe" />
    </div>

    <div class="form-group">
        <input class="form-control" type="email" name="email" value="<?= $user['email'] ?>" placeholder="Nom d'utilisateur" />
    </div>

    <div class="form-group">
        <input class="form-control" type="date" name="birthdate" value="<?= $user['birthdate'] ?>" placeholder="Date de naissance" />
    </div>

    <div class="form-group">
        <input class="form-control" type="text" name="lastname" value="<?= $user['lastname'] ?>" placeholder="Nom" />
    </div>

    <div class="form-group">
        <input class="form-control" type="text" name="firstname" value="<?= $user['firstname'] ?>" placeholder="Prénom" />
    </div>

    <input class="btn btn-info" type="submit" value="Sauvegarder">
</form>